spring:
  application:
    name: spring-security
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:spring-security
    driver-class-name: org.h2.Driver
    username: b
    password: 1
  h2:
    console:
      path: /h2-console
      enabled: true
token:
  signing:
    key: 322F4428472B4B6250655368566D5970337336763979244226452948404D6351
